In [1]:
import numpy as np
import pandas as pd
import mglearn
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina' 
from matplotlib import font_manager, rc
import seaborn as sns

D:\anaconda\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
D:\anaconda\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [2]:
x = pd.read_csv("variable_total.csv")

In [3]:
x = x.drop(["Unnamed: 0"],axis=1)

In [4]:
x.shape

(1997, 79)

In [5]:
y_onehot = pd.read_csv("train_profile_onehot.csv")

In [6]:
y_onehot

CUS_ID  F20-  F30  F40+  M20-  M30  M40+
0          1     0    0     0     0    0     1
1          2     1    0     0     0    0     0
2          4     0    0     0     0    1     0
3          5     0    0     0     0    0     1
4          8     0    0     0     0    1     0
...      ...   ...  ...   ...   ...  ...   ...
1992    2494     0    0     0     1    0     0
1993    2495     0    1     0     0    0     0
1994    2496     0    0     0     0    0     1
1995    2498     0    0     1     0    0     0
1996    2499     0    0     0     1    0     0

[1997 rows x 7 columns]

In [7]:
y = pd.read_csv("train_profile_group.csv")

In [8]:
y

CUS_ID  GROUP
0          1      5
1          2      0
2          4      4
3          5      5
4          8      4
...      ...    ...
1992    2494      3
1993    2495      1
1994    2496      5
1995    2498      2
1996    2499      3

[1997 rows x 2 columns]

---
train test 나누기 <br>
minmaxscaled

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
y=y.iloc[:,1]

In [11]:
y_list=y.values.tolist()

In [12]:
y_list=np.array(y_list)

In [13]:
y_list

array([5, 0, 4, ..., 5, 2, 3])

-----
원핫 한거 split

In [14]:
y_onehot=y_onehot.iloc[:,1:7]

In [15]:
y_list_one = y_onehot.values.tolist()

In [16]:
y_list_one = np.array(y_list_one)

In [17]:
y_list_one

array([[0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [21]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score

---

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
pipe = make_pipeline(MinMaxScaler(),KNeighborsClassifier(n_neighbors = 9))

In [25]:
scores = cross_val_score(pipe,x,y_list)

----

In [31]:
from sklearn.model_selection import RepeatedStratifiedKFold

In [32]:
kfold =RepeatedStratifiedKFold()

In [33]:
scores = cross_val_score(pipe,x,y_list,cv=kfold)

In [34]:
scores.mean()

0.2898367167919799

In [36]:
# 원핫 x sclaued x
aa = KNeighborsClassifier(n_neighbors = 9)
scores = cross_val_score(aa,x,y_list,cv=kfold)

In [37]:
scores.mean()

0.23990313283208017

---
로지스틱 회귀

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
pipe = make_pipeline(MinMaxScaler(),LogisticRegression(C = 1))
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

D:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
D:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_ms

0.3760634085213032

In [43]:
aa = LogisticRegression(C = 1)
scores = cross_val_score(aa,x,y_list,cv=kfold)

D:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
D:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_ms

In [44]:
scores.mean()

0.3439641604010025

---
선형 SVC

In [45]:
from sklearn.svm import LinearSVC

In [46]:
pipe = make_pipeline(MinMaxScaler(),LinearSVC(C = 100))
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\sv

0.3639461152882205

In [47]:
aa = LinearSVC(C = 100)
scores = cross_val_score(aa,x,y_list,cv=kfold)
scores.mean()

D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\sv

0.24616666666666667

---
결정트리

In [48]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
pipe = make_pipeline(MinMaxScaler(),DecisionTreeClassifier(max_depth = 14))
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

0.2744076441102757

In [50]:
aa = DecisionTreeClassifier(max_depth = 14)
scores = cross_val_score(aa,x,y_list,cv=kfold)
scores.mean()

0.2671951127819549

---
랜덤 포레스트

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
pipe = make_pipeline(MinMaxScaler(),RandomForestClassifier(max_depth = 16,n_estimators=100))
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

0.38697406015037594

In [53]:
aa = RandomForestClassifier(max_depth =16, n_estimators=100)
scores = cross_val_score(aa,x,y_list,cv=kfold)
scores.mean()

0.38317581453634075

------
그레디언트 부스팅 회귀

In [55]:
from sklearn.ensemble import GradientBoostingClassifier

In [57]:
pipe = make_pipeline(MinMaxScaler(), GradientBoostingClassifier(learning_rate = 0.1, max_features= 4 , n_estimators=50))
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

0.3998461152882205

In [61]:
aa = GradientBoostingClassifier(learning_rate = 0.1, max_features= 4 , n_estimators=50)
scores = cross_val_score(aa,x,y_list,cv=kfold)
scores.mean()

0.39750075187969924

---
선형 svc

In [62]:
from sklearn.svm import LinearSVC

In [63]:
pipe = make_pipeline(MinMaxScaler(), LinearSVC())
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

0.37300814536340854

In [64]:
aa = LinearSVC()
scores = cross_val_score(aa,x,y_list,cv=kfold)
scores.mean()

D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\sv

0.25798483709273184

----
SVC

In [65]:
from sklearn.svm import SVC

In [66]:
pipe = make_pipeline(MinMaxScaler(), SVC(C = 10 , gamma = 0.1))
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

0.3738104010025062

In [67]:
aa =  SVC(C = 10 , gamma = 0.1)
scores = cross_val_score(aa,x,y_list,cv=kfold)
scores.mean()

0.29744611528822057

---
신경망

In [68]:
from sklearn.neural_network import MLPClassifier

In [69]:
pipe = make_pipeline(MinMaxScaler(), MLPClassifier(solver='adam' ,alpha =0.01))
scores = cross_val_score(pipe,x,y_list,cv=kfold)
scores.mean()

D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklear

0.375410776942356

In [70]:
aa =  MLPClassifier(solver='adam' ,alpha =0.01)
scores = cross_val_score(aa,x,y_list,cv=kfold)
scores.mean()

D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\anaconda\lib\site-packages\sklear

0.288587969924812

--------
# 최종

---
랜덤 포레스트

In [74]:
from sklearn.ensemble import RandomForestClassifier

In [76]:
pipe = make_pipeline(MinMaxScaler(),RandomForestClassifier(max_depth = 16,n_estimators=100))
scores_1 = cross_val_score(pipe,x,y_list,cv=kfold)
scores_1.mean()

0.385279573934837

In [77]:
aa = RandomForestClassifier(max_depth =16, n_estimators=100)
scores_2 = cross_val_score(aa,x,y_list,cv=kfold)
scores_2.mean()

0.38693020050125315

In [82]:
scores_1

array([0.36      , 0.4075    , 0.39348371, 0.35588972, 0.42105263,
       0.425     , 0.36      , 0.39849624, 0.4085213 , 0.39598997,
       0.395     , 0.3875    , 0.40100251, 0.36591479, 0.37593985,
       0.375     , 0.3425    , 0.41353383, 0.37593985, 0.43358396,
       0.37      , 0.3675    , 0.41102757, 0.38847118, 0.35087719,
       0.42      , 0.385     , 0.37092732, 0.37343358, 0.38095238,
       0.3975    , 0.325     , 0.36340852, 0.38596491, 0.36090226,
       0.415     , 0.36      , 0.4085213 , 0.40100251, 0.36842105,
       0.4125    , 0.4       , 0.39598997, 0.38095238, 0.36842105,
       0.3675    , 0.4       , 0.36842105, 0.38596491, 0.38847118])

In [83]:
scores_2

array([0.405     , 0.365     , 0.38095238, 0.37844612, 0.40350877,
       0.4       , 0.42      , 0.38596491, 0.34085213, 0.36842105,
       0.375     , 0.3925    , 0.37092732, 0.40601504, 0.38596491,
       0.3775    , 0.3975    , 0.37844612, 0.4160401 , 0.41102757,
       0.4025    , 0.4025    , 0.35839599, 0.39097744, 0.37343358,
       0.395     , 0.365     , 0.37593985, 0.42606516, 0.34837093,
       0.375     , 0.335     , 0.41854637, 0.41102757, 0.4085213 ,
       0.3775    , 0.395     , 0.38847118, 0.38847118, 0.39849624,
       0.385     , 0.3875    , 0.38596491, 0.34586466, 0.39348371,
       0.3875    , 0.4025    , 0.35588972, 0.41353383, 0.39598997])

------
그레디언트 부스팅 회귀

In [78]:
from sklearn.ensemble import GradientBoostingClassifier

In [86]:
pipe = make_pipeline(MinMaxScaler(), GradientBoostingClassifier(learning_rate = 0.1, max_features= 4 , n_estimators=50))
scores_3 = cross_val_score(pipe,x,y_list,cv=kfold)
scores_3.mean()

0.39854110275689214

In [87]:
aa = GradientBoostingClassifier(learning_rate = 0.1, max_features= 4 , n_estimators=50)
scores_4 = cross_val_score(aa,x,y_list,cv=kfold)
scores_4.mean()

0.3983011278195489

In [88]:
scores_3

array([0.4375    , 0.3675    , 0.38345865, 0.37092732, 0.40100251,
       0.3725    , 0.385     , 0.43107769, 0.4160401 , 0.40350877,
       0.385     , 0.41      , 0.40350877, 0.39598997, 0.39849624,
       0.425     , 0.4025    , 0.39097744, 0.37343358, 0.4235589 ,
       0.4175    , 0.4175    , 0.4085213 , 0.40100251, 0.4160401 ,
       0.4275    , 0.395     , 0.38095238, 0.36591479, 0.41102757,
       0.4075    , 0.395     , 0.31578947, 0.41854637, 0.4160401 ,
       0.43      , 0.4225    , 0.39598997, 0.36842105, 0.36591479,
       0.4025    , 0.4       , 0.35839599, 0.39598997, 0.4085213 ,
       0.405     , 0.4       , 0.38095238, 0.42857143, 0.39348371])