In [2]:
import numpy as np
import pandas as pd
import mglearn
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina' 
from matplotlib import font_manager, rc
import seaborn as sns

D:\anaconda\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
D:\anaconda\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [3]:
df = pd.read_csv("variable_total.csv")

In [4]:
df = df.drop(["Unnamed: 0"],axis=1)

In [5]:
answer=pd.read_csv("train_datapoint_profile.csv")
answer.shape

(1997, 5)

In [6]:
df.shape

(1997, 79)

In [7]:
df.isnull().sum().sort_values(ascending=False)

v7_pm_timeAVG           0
v2_Sat_count            0
v1_Community_count      0
v1_Study_count          0
v2_Mon_count            0
                       ..
v5_Daum_Search_count    0
v5_Daum_Mail_count      0
v5_Daum_Cafe_count      0
v5_Daum_Media_count     0
CUS_ID                  0
Length: 79, dtype: int64

In [9]:
answer=answer.sort_values(by="CUS_ID")

In [10]:
y_data_onehot = pd.read_csv("train_profile_onehot.csv")

In [11]:
y_data_onehot

CUS_ID  F20-  F30  F40+  M20-  M30  M40+
0          1     0    0     0     0    0     1
1          2     1    0     0     0    0     0
2          4     0    0     0     0    1     0
3          5     0    0     0     0    0     1
4          8     0    0     0     0    1     0
...      ...   ...  ...   ...   ...  ...   ...
1992    2494     0    0     0     1    0     0
1993    2495     0    1     0     0    0     0
1994    2496     0    0     0     0    0     1
1995    2498     0    0     1     0    0     0
1996    2499     0    0     0     1    0     0

[1997 rows x 7 columns]

In [12]:
y_data = pd.read_csv("train_profile_group.csv")

In [13]:
y_data

CUS_ID  GROUP
0          1      5
1          2      0
2          4      4
3          5      5
4          8      4
...      ...    ...
1992    2494      3
1993    2495      1
1994    2496      5
1995    2498      2
1996    2499      3

[1997 rows x 2 columns]

-----

In [14]:
from sklearn.preprocessing import MinMaxScaler 

In [15]:
scaler = MinMaxScaler()
scaler.fit(df)
x_data =scaler.transform(df)

In [16]:
x_data.shape

(1997, 79)

In [14]:
a=answer.loc[:,["CUS_ID","AGE"]]

In [15]:
y_data = a.values
y_data=y_data.reshape(-1,2)

In [16]:
y_data

array([[   1,   40],
       [   2,   20],
       [   4,   30],
       ...,
       [2496,   50],
       [2498,   40],
       [2499,   20]], dtype=int64)

In [71]:
y_data.shape

(1997, 7)

In [18]:
x_data

array([[0.00000000e+00, 0.00000000e+00, 1.42870102e-02, ...,
        7.52850075e-04, 1.13257853e-01, 8.34387464e-02],
       [4.00320256e-04, 1.15321252e-02, 8.16400581e-04, ...,
        2.17143472e-01, 1.67594501e-01, 1.63777092e-01],
       [1.20096077e-03, 8.23723229e-04, 4.53555878e-05, ...,
        3.89653689e-01, 1.85438577e-01, 1.32835697e-01],
       ...,
       [9.98799039e-01, 0.00000000e+00, 4.08200290e-04, ...,
        3.93633039e-02, 2.00428839e-01, 2.81563510e-01],
       [9.99599680e-01, 5.76606260e-03, 0.00000000e+00, ...,
        5.37750054e-04, 1.12369716e-01, 1.46576048e-01],
       [1.00000000e+00, 0.00000000e+00, 7.25689405e-04, ...,
        4.30200043e-02, 2.17874810e-01, 1.44855181e-01]])

In [19]:
x_data.shape

(1997, 79)

---
knn

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [54]:
knn = KNeighborsClassifier(n_neighbors=1)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data)

In [19]:
from sklearn.multioutput import MultiOutputClassifier

knn = KNeighborsClassifier(n_neighbors=3)
classifier = MultiOutputClassifier(knn, n_jobs=-1)
classifier.fit(x_train,y_train)
classifier.score(x_train,y_train)

0.15364061456245826

----
파이프라인 

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import GridSearchCV

In [21]:
x_train,x_test,y_train,y_test = train_test_split(df,y_data)

In [22]:
pipe = Pipeline([("scaler",MinMaxScaler()),("svm",SVC())])

In [23]:
pipe.steps

[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
 ('svm',
  SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
      decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
      max_iter=-1, probability=False, random_state=None, shrinking=True,
      tol=0.001, verbose=False))]

In [44]:
y_train

array([3, 1, 5, ..., 5, 2, 3])

In [41]:
pipe.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('svm',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='scale', kernel='rbf', max_iter=-1,
                     probability=False, random_state=None, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [45]:
pipe.score(x_test,y_test)

0.33

In [102]:
x_train.shape

(1497, 79)

In [103]:
y_train.shape

(1497, 7)

---
minmaxscaler

In [35]:
x_train,x_test,y_train,y_test = train_test_split(df,y_list)

In [26]:
scaler = MinMaxScaler()
scaler.fit(x_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [27]:
x_train_scaled =scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [29]:
y=y_data.iloc[:,1]

In [30]:
y_list=y.values.tolist()

In [31]:
y_list=np.array(y_list)

In [33]:
y_list

array([5, 0, 4, ..., 5, 2, 3])

In [36]:
x_train_scaled

array([[5.12409928e-02, 2.96622614e-01, 2.26777939e-04, ...,
        3.20929232e-01, 1.27357649e-01, 1.65756536e-01],
       [1.43714972e-01, 1.76211454e-02, 0.00000000e+00, ...,
        0.00000000e+00, 1.49403525e-01, 1.36401524e-01],
       [8.81505204e-01, 5.87371512e-03, 1.81422351e-04, ...,
        2.97913530e-02, 9.77943596e-02, 1.07441531e-01],
       ...,
       [3.36269015e-02, 2.05580029e-02, 4.53555878e-05, ...,
        7.78662078e-02, 4.99329901e-02, 1.04290783e-01],
       [3.61489191e-01, 7.34214391e-03, 0.00000000e+00, ...,
        3.37707034e-02, 2.99300812e-01, 2.73862412e-01],
       [9.92794235e-01, 1.76211454e-02, 4.08200290e-04, ...,
        4.62465046e-02, 1.11990557e-01, 1.55013863e-01]])

In [37]:
y_train

array([3, 1, 5, ..., 5, 2, 3])

---

In [38]:
clf= KNeighborsClassifier(n_neighbors=3)

In [39]:
clf.fit(x_train_scaled,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [40]:
clf.score(x_test_scaled,y_test)

0.184

-----

In [168]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(x_train_scaled,y_train)

In [179]:
lr.score(x_train_scaled,y_train)

D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.034976406015607135

In [181]:
lr.score(x_test_scaled,y_test)

D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


-0.04158419153584213

----

In [190]:
from sklearn.linear_model import Ridge

ridge =Ridge(alpha=0.1).fit(x_train_scaled,y_train)

In [191]:
ridge.score(x_train_scaled,y_train)

D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


0.04547085876230523

In [192]:
ridge.score(x_test_scaled,y_test)

D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


-0.03475146635405325

----

In [193]:
from sklearn.linear_model import Lasso

In [196]:
lasso=Lasso().fit(x_train_scaled,y_train)
print(lasso.score(x_train_scaled,y_train))
print(lasso.score(x_test_scaled,y_test))
print(np.sum(lasso.coef_ !=0))


0.0
-0.002280703679715687
0


D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)
D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_av

In [203]:
lasso1=Lasso(alpha=0.0001,max_iter=100000).fit(x_train_scaled,y_train)
print(lasso1.score(x_train_scaled,y_train))
print(lasso1.score(x_test_scaled,y_test))
print(np.sum(lasso1.coef_ !=0))

0.04140391606281347
-0.02611471026218096
368


D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)
D:\anaconda\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_av

----

In [204]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

In [207]:
logreg = LogisticRegression().fit(x_train_scaled,y_train)

ValueError: bad input shape (1497, 6)

In [206]:
print(logreg.score(x_train_scaled,y_train))

NameError: name 'logreg' is not defined