## Multivariable linear regression

Hypothesis <Br>
Cost function<br>
Gradient descent algorithm

여러개의 input이 있으면 Multivariable linear

1개의 input <br>
H(x) = Wx + b<br>
여러개(n개)의 input<br>
H(x1,x2,x3) = w1x1 + w2x2 + w3x3+...wnxn + b

input 이 많아 질수록 복잡해진다. <br>
그래서 Matrix를 이용한다. (곱셈을 이용) 
 > H(X)  = XW 

데이터를 인스턴스 라고 함

크기는 [x1 ,y1] , [x2,y2] 라고하면 <br>
 y1 과 x2 의 크기를 같아야 하고  곱셈을 하였을 때 결과는 <br>
 [x1 , y2] 의 크기로 나옴 <br>
 x1 = 데이터의 갯수<br>
 y1 = x 의 갯수 <br> 
 y2 = Y값 1 개 

이걸로 W = [x2,y2] 의 크기를 알아낼 수 있다.

실제 구현은 매트릭스를 많이 사용한다. <br>
매트릭스 사용하는것은H(x) = XW 이런 식으로 표현 

In [1]:
import tensorflow as tf

D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#데이터정의
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]
# fid_tict 로 하기 위한 선언
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]),name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]),name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]),name = 'weight3')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

hypothesis = x1 * w1 + x2* w2 + x3*w3 +b 


In [4]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#optimizer 을 0.01 or 0.001 을 하면 복잡해짐
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [6]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                            feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y: y_data})
    if step % 10 ==0:
        print(step, "Cost ",cost_val,"\nPrediction:\n",hy_val)
# 처음에는 cost가 높은데 실행할수록 작아지는 것을 확인
# 2000 Cost  3.1211815 
# Prediction:
# [154.32784 182.87228 181.94827 195.14641 140.93439]
# 마지막 값이 y값이랑 비숫해 진것을 확인 
# 지금은 3개라서 이정도 이지만 많아지면 복잡해지기에 거의 사용을 안함

0 Cost  7.4806786 
Prediction:
 [155.8953  181.80594 182.43915 195.41992 139.60373]
10 Cost  7.4452796 
Prediction:
 [155.88521 181.81282 182.436   195.41805 139.6124 ]
20 Cost  7.41007 
Prediction:
 [155.87517 181.81969 182.43288 195.41621 139.62106]
30 Cost  7.3750443 
Prediction:
 [155.86511 181.8265  182.42973 195.41434 139.62967]
40 Cost  7.3402433 
Prediction:
 [155.85513 181.83334 182.42664 195.4125  139.63828]
50 Cost  7.305551 
Prediction:
 [155.84512 181.84012 182.4235  195.41068 139.64685]
60 Cost  7.2710953 
Prediction:
 [155.83517 181.84691 182.4204  195.40886 139.6554 ]
70 Cost  7.2368307 
Prediction:
 [155.82526 181.85368 182.41731 195.40703 139.66393]
80 Cost  7.2027435 
Prediction:
 [155.81534 181.86041 182.41422 195.4052  139.67241]
90 Cost  7.1688147 
Prediction:
 [155.80548 181.86716 182.41113 195.4034  139.68091]
100 Cost  7.135124 
Prediction:
 [155.79564 181.87387 182.40808 195.4016  139.68935]
110 Cost  7.101545 
Prediction:
 [155.78581 181.88055 182.40498 195.3

In [16]:
# Matrix 사용
# 각각이 x1, x2 ,x3 의 값
x_data = [[73.,80.,75.],[93.,88.,93.],
         [89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

# shape x데이터는 n개를 가질 것이다 (지금은 5개임)
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X, w)+ b

# 여기 부분만 간단해짐 ( Matrix 의 장점 )

In [17]:
cost = tf.reduce_mean(tf.square(hypothesis- Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train= optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [18]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis,train], feed_dict = {X : x_data, Y: y_data})
    if step % 10 == 0 :
        print(step, "Cost: ",cost_val,"\nPrediction\n",hy_val)
# 결과 값은 비슷해지는 것을 확인 

0 Cost:  23914.574 
Prediction
 [[11.856267]
 [20.985653]
 [16.829113]
 [22.486103]
 [14.328214]]
10 Cost:  5.2648225 
Prediction
 [[148.64383]
 [185.39056]
 [178.82202]
 [198.891  ]
 [139.72797]]
20 Cost:  5.0428886 
Prediction
 [[149.05962]
 [185.88678]
 [179.31287]
 [199.42422]
 [140.10666]]
30 Cost:  5.03981 
Prediction
 [[149.0628 ]
 [185.88707]
 [179.31506]
 [199.42532]
 [140.1071 ]]
40 Cost:  5.036784 
Prediction
 [[149.06471]
 [185.88585]
 [179.31578]
 [199.4248 ]
 [140.10637]]
50 Cost:  5.033722 
Prediction
 [[149.06664]
 [185.88464]
 [179.31651]
 [199.42429]
 [140.10567]]
60 Cost:  5.030684 
Prediction
 [[149.06854]
 [185.88344]
 [179.31723]
 [199.42377]
 [140.10497]]
70 Cost:  5.0276527 
Prediction
 [[149.07047]
 [185.88225]
 [179.31796]
 [199.42326]
 [140.10426]]
80 Cost:  5.024631 
Prediction
 [[149.07236]
 [185.88106]
 [179.31868]
 [199.42274]
 [140.10358]]
90 Cost:  5.0215936 
Prediction
 [[149.07428]
 [185.87987]
 [179.31941]
 [199.42224]
 [140.10289]]
100 Cost:  5.0185