In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline
import seaborn as sns

D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
df_train=pd.read_csv("train.csv")
df_test=pd.read_csv("test.csv")

In [4]:
col = ["MSZoning","LotShape","HouseStyle","Neighborhood","Exterior1st","Exterior2nd","Foundation","MasVnrType","ExterQual","BsmtQual","BsmtFinType1","HeatingQC","KitchenQual","FireplaceQu","GarageType","GarageFinish"]

In [5]:
x_train=df_train.loc[:,col]
x_test=df_test.loc[:,col]

In [6]:
x_test.isnull().sum().sort_values(ascending=False)

FireplaceQu     730
GarageFinish     78
GarageType       76
BsmtQual         44
BsmtFinType1     42
MasVnrType       16
MSZoning          4
KitchenQual       1
Exterior2nd       1
Exterior1st       1
HeatingQC         0
ExterQual         0
Foundation        0
Neighborhood      0
HouseStyle        0
LotShape          0
dtype: int64

In [7]:
x_train.loc[x_train.isnull()["GarageFinish"],:] = x_train.loc[x_train.isnull()["GarageFinish"],:].fillna(value="None")
x_train.loc[x_train.isnull()["GarageType"],:] = x_train.loc[x_train.isnull()["GarageType"],:].fillna(value="None")
x_train.loc[x_train.isnull()["FireplaceQu"],:] = x_train.loc[x_train.isnull()["FireplaceQu"],:].fillna(value="None")
x_train.loc[x_train.isnull()["BsmtQual"],:] = x_train.loc[x_train.isnull()["BsmtQual"],:].fillna(value="None")
x_train.loc[x_train.isnull()["BsmtFinType1"],:] = x_train.loc[x_train.isnull()["BsmtFinType1"],:].fillna(value="None")
x_train.loc[x_train.isnull()["MasVnrType"],:] = x_train.loc[x_train.isnull()["MasVnrType"],:].fillna(value="None")

In [8]:
x_test.loc[x_test.isnull()["KitchenQual"],:] = x_test.loc[x_test.isnull()["KitchenQual"],:].fillna(value="None")
x_test.loc[x_test.isnull()["GarageFinish"],:] = x_test.loc[x_test.isnull()["GarageFinish"],:].fillna(value="None")
x_test.loc[x_test.isnull()["GarageType"],:] = x_test.loc[x_test.isnull()["GarageType"],:].fillna(value="None")
x_test.loc[x_test.isnull()["FireplaceQu"],:] = x_test.loc[x_test.isnull()["FireplaceQu"],:].fillna(value="None")
x_test.loc[x_test.isnull()["BsmtQual"],:] = x_test.loc[x_test.isnull()["BsmtQual"],:].fillna(value="None")
x_test.loc[x_test.isnull()["BsmtFinType1"],:] = x_test.loc[x_test.isnull()["BsmtFinType1"],:].fillna(value="None")
x_test.loc[x_test.isnull()["MasVnrType"],:] = x_test.loc[x_test.isnull()["MasVnrType"],:].fillna(value="None")
x_test.loc[x_test.isnull()["Exterior2nd"],:] = x_test.loc[x_test.isnull()["Exterior2nd"],:].fillna(value="None")
x_test.loc[x_test.isnull()["Exterior1st"],:] = x_test.loc[x_test.isnull()["Exterior1st"],:].fillna(value="None")
x_test.loc[x_test.isnull()["MSZoning"],:] = x_test.loc[x_test.isnull()["MSZoning"],:].fillna(value="None")

In [9]:
add_x = pd.concat([x_train,x_test])
one_hot = pd.get_dummies(add_x)
train_onehot=one_hot.iloc[0:1460,:]

In [10]:
test_onehot=one_hot.iloc[1460:2920,:]

---

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
x_data =df_train.loc[:,["OverallQual","YearBuilt","YearRemodAdd","MasVnrArea","TotalBsmtSF","1stFlrSF","GrLivArea","FullBath","TotRmsAbvGrd","Fireplaces","GarageCars","GarageArea"]]

In [13]:
x_data.isnull().sum().sort_values(ascending=False)

MasVnrArea      8
GarageArea      0
GarageCars      0
Fireplaces      0
TotRmsAbvGrd    0
FullBath        0
GrLivArea       0
1stFlrSF        0
TotalBsmtSF     0
YearRemodAdd    0
YearBuilt       0
OverallQual     0
dtype: int64

In [14]:
x_data.loc[x_data.isnull()["MasVnrArea"],:] = x_data.loc[x_data.isnull()["MasVnrArea"],:].fillna(value=x_data["MasVnrArea"].mean())

In [15]:
x_data_train = pd.concat([train_onehot,x_data], axis=1)

In [16]:
scaler = MinMaxScaler()

In [17]:
scaler.fit(x_data_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
x_data =scaler.transform(x_data_train)

In [19]:
y_data = df_train.iloc[:,-1]
y_data = y_data.values
y_data=y_data.reshape(-1,1)

In [20]:
print(x_data.shape)
print(y_data.shape)

(1460, 141)
(1460, 1)


In [29]:
X = tf.placeholder(tf.float32, shape=[None,141])
Y = tf.placeholder(tf.float32, shape=[None,1])


W = tf.Variable(tf.random_normal([141,1],name='weight'))
b = tf.Variable(tf.random_normal([1],name='bias'))

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1)
train = optimizer.minimize(cost)

In [30]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(200001):
    cost_val, hy_val, _ = sess.run(
        [cost,hypothesis,train],
        feed_dict={X:x_data, Y:y_data})
    if step % 2000 == 0:
        print(step,"Cost : ",cost_val,
             "\nPreadiction\n",hy_val)

0 Cost :  39040225000.0 
Preadiction
 [[-5.4088054]
 [-1.4954491]
 [-4.7134786]
 ...
 [-2.4167306]
 [-1.6126257]
 [ 2.1389644]]
2000 Cost :  892772860.0 
Preadiction
 [[207273.73 ]
 [204321.77 ]
 [209661.94 ]
 ...
 [280263.38 ]
 [131496.89 ]
 [126973.914]]
4000 Cost :  883596200.0 
Preadiction
 [[206378.89]
 [205569.9 ]
 [209671.88]
 ...
 [281330.72]
 [131981.8 ]
 [126897.23]]
6000 Cost :  878257500.0 
Preadiction
 [[206024.94]
 [205502.92]
 [209936.42]
 ...
 [282150.94]
 [132234.9 ]
 [127002.96]]
8000 Cost :  874571900.0 
Preadiction
 [[205866.64]
 [205315.1 ]
 [210149.75]
 ...
 [282815.  ]
 [132392.47]
 [127095.84]]
10000 Cost :  871913200.0 
Preadiction
 [[205785.06]
 [205133.84]
 [210321.9 ]
 ...
 [283358.72]
 [132511.81]
 [127158.31]]
12000 Cost :  869946430.0 
Preadiction
 [[205736.25]
 [204976.9 ]
 [210465.73]
 ...
 [283820.22]
 [132615.22]
 [127198.14]]
14000 Cost :  868464500.0 
Preadiction
 [[205702.58]
 [204845.48]
 [210588.86]
 ...
 [284221.5 ]
 [132711.02]
 [127222.76]]
16

----

In [31]:
x_data =df_test.loc[:,["OverallQual","YearBuilt","YearRemodAdd","MasVnrArea","TotalBsmtSF","1stFlrSF","GrLivArea","FullBath","TotRmsAbvGrd","Fireplaces","GarageCars","GarageArea"]]

In [32]:
x_data.loc[x_data.isnull()["MasVnrArea"],:] = x_data.loc[x_data.isnull()["MasVnrArea"],:].fillna(value=x_data["MasVnrArea"].mean())
x_data.loc[x_data.isnull()["GarageCars"],:] = x_data.loc[x_data.isnull()["GarageCars"],:].fillna(value=x_data["GarageCars"].mean())
x_data.loc[x_data.isnull()["GarageArea"],:] = x_data.loc[x_data.isnull()["GarageArea"],:].fillna(value=x_data["GarageArea"].mean())
x_data.loc[x_data.isnull()["TotalBsmtSF"],:] = x_data.loc[x_data.isnull()["TotalBsmtSF"],:].fillna(value=x_data["TotalBsmtSF"].mean())

In [33]:
x_data.isnull().sum().sort_values(ascending=False)
x_data_test = pd.concat([test_onehot,x_data], axis=1)
x_data_test =scaler.transform(x_data_test)
x_data_test.shape

(1459, 141)

---

In [34]:
sess.run(hypothesis, feed_dict={X:x_data_test})

array([[107945.62],
       [146355.05],
       [175739.16],
       ...,
       [155508.6 ],
       [ 95945.25],
       [202258.1 ]], dtype=float32)

In [35]:
sample = pd.read_csv("sample_submission.csv")
sample['SalePrice']=sess.run(hypothesis, feed_dict={X:x_data_test})

In [36]:
sample.to_csv("sample10.csv",index=False)

In [37]:
def log_rmse(predict_y, y_val):
    if predict_y.shape[0] != y_val.shape[0]:
        error_msg = "not matched length of arrays"
        return error_msg
    else:
        RMSE_log = np.sqrt(((np.log(predict_y) - np.log(y_val))**2).mean())
        return RMSE_log

In [38]:
y_train =df_train.iloc[:,-1]

In [39]:
log_rmse(hy_val.reshape(-1,), y_train)

0.14306125382330412