In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline
import seaborn as sns

D:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [7]:
df_train=pd.read_csv("train.csv")
df_test=pd.read_csv("test.csv")

-----

In [4]:
cal = ['MSZoning'
,'Alley'
,'LotShape'
,'LotConfig'
,'BldgType'
,'HouseStyle'
,'RoofStyle'
,'MasVnrType'
,'ExterQual'
,'Foundation'
,'BsmtQual'
,'BsmtCond'
,'BsmtExposure'
,'BsmtFinType1'
,'HeatingQC'
,'KitchenQual'
,'FireplaceQu'
,'GarageType'
,'GarageFinish'
,'GarageQual'
,'PoolQC'
,'Fence']

In [8]:
x_train=df_train.loc[:,cal]
x_test=df_test.loc[:,cal]

In [10]:
x_train.shape

(1460, 22)

In [11]:
x_test.shape

(1459, 22)

In [9]:
add_x = pd.concat([x_train,x_test])

In [12]:
one_hot = pd.get_dummies(add_x)

In [13]:
train_onehot=one_hot.iloc[0:1460,:]

In [14]:
test_onehot=one_hot.iloc[1460:2920,:]

----

In [15]:
x_n =df_train.loc[:,["OverallQual","YearBuilt","YearRemodAdd","MasVnrArea","TotalBsmtSF","1stFlrSF","GrLivArea","FullBath","TotRmsAbvGrd","Fireplaces","GarageYrBlt","GarageCars","GarageArea"]]

In [16]:
x_data_train = pd.concat([train_onehot,x_n], axis=1)

In [17]:
x_data_train.shape

(1460, 115)

In [22]:
x_data_train.isnull().sum().sort_values(ascending=False)

GarageYrBlt           81
MasVnrArea             8
GarageArea             0
ExterQual_Gd           0
RoofStyle_Flat         0
RoofStyle_Gable        0
RoofStyle_Gambrel      0
RoofStyle_Hip          0
RoofStyle_Mansard      0
RoofStyle_Shed         0
MasVnrType_BrkCmn      0
MasVnrType_BrkFace     0
MasVnrType_None        0
MasVnrType_Stone       0
ExterQual_Ex           0
ExterQual_Fa           0
ExterQual_TA           0
HouseStyle_SFoyer      0
Foundation_BrkTil      0
Foundation_CBlock      0
Foundation_PConc       0
Foundation_Slab        0
Foundation_Stone       0
Foundation_Wood        0
BsmtQual_Ex            0
BsmtQual_Fa            0
BsmtQual_Gd            0
BsmtQual_TA            0
BsmtCond_Fa            0
HouseStyle_SLvl        0
                      ..
Fireplaces             0
GarageType_CarPort     0
GarageType_BuiltIn     0
GarageType_Basment     0
HeatingQC_Gd           0
BsmtExposure_Gd        0
BsmtExposure_Mn        0
BsmtExposure_No        0
BsmtFinType1_ALQ       0


In [26]:
x_data=x_data_train.drop("GarageYrBlt",axis=1)

x_data.loc[x_data.isnull()["MasVnrArea"],:] = 
        x_data.loc[x_data.isnull()["MasVnrArea"],:].fillna(
            value=x_data["MasVnrArea"].mean())

In [28]:
x_data = x_data.values

In [29]:
len(x_data)

1460

In [30]:
y_data = df_train.iloc[:,-1]
y_data.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [31]:
y_data = y_data.values
y_data=y_data.reshape(-1,1)

In [32]:
print(x_data.shape)
print(y_data.shape)

(1460, 114)
(1460, 1)


In [39]:
X = tf.placeholder(tf.float32, shape=[None,114])
Y = tf.placeholder(tf.float32, shape=[None,1])


W = tf.Variable(tf.random_normal([114,1],name='weight'))
b = tf.Variable(tf.random_normal([1],name='bias'))

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-8)
train = optimizer.minimize(cost)

In [40]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(200001):
    cost_val, hy_val, _ = sess.run(
        [cost,hypothesis,train],
        feed_dict={X:x_data, Y:y_data})
    if step % 2000 == 0:
        print(step,"Cost : ",cost_val,
             "\nPreadiction\n",hy_val)

0 Cost :  40331500000.0 
Preadiction
 [[-2476.2488]
 [-3913.6658]
 [-2749.4976]
 ...
 [-3062.1667]
 [-3226.3801]
 [-3668.407 ]]
2000 Cost :  2082127200.0 
Preadiction
 [[193229.38]
 [168253.5 ]
 [204373.53]
 ...
 [219643.31]
 [130378.21]
 [154129.9 ]]
4000 Cost :  2059617300.0 
Preadiction
 [[196916.33]
 [167395.42]
 [208246.05]
 ...
 [214077.17]
 [127347.01]
 [150446.33]]
6000 Cost :  2057541600.0 
Preadiction
 [[197880.1 ]
 [167234.73]
 [209282.83]
 ...
 [212593.66]
 [126510.82]
 [149523.73]]
8000 Cost :  2056880400.0 
Preadiction
 [[198148.55]
 [167226.02]
 [209579.  ]
 ...
 [212165.12]
 [126243.7 ]
 [149309.86]]
10000 Cost :  2056328600.0 
Preadiction
 [[198237.58]
 [167247.81]
 [209677.64]
 ...
 [212005.39]
 [126127.2 ]
 [149279.84]]
12000 Cost :  2055794400.0 
Preadiction
 [[198279.77]
 [167274.25]
 [209722.08]
 ...
 [211912.56]
 [126051.69]
 [149297.77]]
14000 Cost :  2055269500.0 
Preadiction
 [[198310.11]
 [167299.89]
 [209751.78]
 ...
 [211838.14]
 [125987.43]
 [149327.7 ]]
1

----

In [41]:
x_n_test =df_test.loc[:,["OverallQual","YearBuilt","YearRemodAdd","MasVnrArea","TotalBsmtSF","1stFlrSF","GrLivArea","FullBath","TotRmsAbvGrd","Fireplaces","GarageYrBlt","GarageCars","GarageArea"]]

In [42]:
x_data_test = pd.concat([test_onehot,x_n_test], axis=1)

In [44]:
x_data_test.isnull().sum().sort_values(ascending=False)

GarageYrBlt           78
MasVnrArea            15
GarageArea             1
TotalBsmtSF            1
GarageCars             1
RoofStyle_Flat         0
RoofStyle_Gable        0
RoofStyle_Gambrel      0
RoofStyle_Hip          0
ExterQual_Fa           0
RoofStyle_Mansard      0
RoofStyle_Shed         0
MasVnrType_BrkCmn      0
MasVnrType_BrkFace     0
MasVnrType_None        0
MasVnrType_Stone       0
ExterQual_Ex           0
Foundation_BrkTil      0
ExterQual_Gd           0
ExterQual_TA           0
HouseStyle_SFoyer      0
Foundation_CBlock      0
Foundation_PConc       0
Foundation_Slab        0
Foundation_Stone       0
Foundation_Wood        0
BsmtQual_Ex            0
BsmtQual_Fa            0
BsmtQual_Gd            0
BsmtQual_TA            0
                      ..
Fireplaces             0
GarageType_CarPort     0
GarageType_Basment     0
BsmtCond_TA            0
HeatingQC_Gd           0
BsmtExposure_Gd        0
BsmtExposure_Mn        0
BsmtExposure_No        0
BsmtFinType1_ALQ       0


In [46]:
x_data=x_data_test.drop("GarageYrBlt",axis=1)
x_data.loc[x_data.isnull()["MasVnrArea"],:] = x_data.loc[x_data.isnull()["MasVnrArea"],:].fillna(value=x_data["MasVnrArea"].mean())

In [47]:
x_data.loc[x_data.isnull()["GarageCars"],:] = x_data.loc[x_data.isnull()["GarageCars"],:].fillna(value=x_data["GarageCars"].mean())
x_data.loc[x_data.isnull()["GarageArea"],:] = x_data.loc[x_data.isnull()["GarageArea"],:].fillna(value=x_data["GarageArea"].mean())

In [48]:
x_data.loc[x_data.isnull()["TotalBsmtSF"],:] = x_data.loc[x_data.isnull()["TotalBsmtSF"],:].fillna(value=x_data["TotalBsmtSF"].mean())

In [51]:
x_data.shape

(1459, 114)

-----

In [53]:
sess.run(hypothesis, feed_dict={X:x_data})

array([[152974.14],
       [168077.55],
       [181129.5 ],
       ...,
       [169820.47],
       [ 92802.14],
       [228779.2 ]], dtype=float32)

In [54]:
sample = pd.read_csv("sample_submission.csv")

In [56]:
sample['SalePrice']=sess.run(hypothesis, feed_dict={X:x_data})

In [57]:
sample.to_csv("sample3.csv",index=False)